# Generated by Django 5.1.13 on 2025-10-27 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_profiles', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmembersindexpage',
            name='header_image',
            field=models.ForeignKey(blank=True, help_text='Header image for the board members page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
