# Generated by Django 5.1.13 on 2025-10-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_profiles', '0002_boardmembersindexpage_header_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardprofilepage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='boardprofilepage',
            name='personal_links',
        ),
        migrations.RemoveField(
            model_name='boardprofilepage',
            name='phone',
        ),
        migrations.AddField(
            model_name='boardprofilepage',
            name='is_board_member',
            field=models.BooleanField(default=True, verbose_name='Is Board Member'),
        ),
        migrations.AddField(
            model_name='boardprofilepage',
            name='is_consultant',
            field=models.BooleanField(default=False, verbose_name='Is Consultant to the Board'),
        ),
    ]
