# Generated by Django 5.1.13 on 2025-10-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_profiles', '0003_remove_boardprofilepage_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardprofilepage',
            name='is_consultant',
        ),
        migrations.RemoveField(
            model_name='boardprofilepage',
            name='term_end',
        ),
        migrations.RemoveField(
            model_name='boardprofilepage',
            name='term_start',
        ),
    ]
