# Generated by Django 5.1.8 on 2025-08-25 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_homepage_show_home_projects'),
    ]

    operations = [
    ]
