# Generated by Django 5.1.7 on 2025-03-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missionary_profiles', '0002_remove_missionaryprofilepage_pictures_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionaryprofilepage',
            name='profile_picture',
        ),
        migrations.DeleteModel(
            name='MissionaryPicture',
        ),
    ]
