# Generated by Django 5.1.7 on 2025-04-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missionary_profiles', '0005_rename_banner_image_missionaryprofilepage_profile_header_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionaryprofilepage',
            name='donation_link',
        ),
        migrations.RemoveField(
            model_name='missionaryprofilepage',
            name='location',
        ),
        migrations.RemoveField(
            model_name='missionaryprofilepage',
            name='personal_links',
        ),
        migrations.RemoveField(
            model_name='missionaryprofilepage',
            name='region',
        ),
        migrations.RemoveField(
            model_name='missionaryprofilepage',
            name='special_project',
        ),
        migrations.RemoveField(
            model_name='missionaryprofilepage',
            name='video_links',
        ),
        migrations.AddField(
            model_name='missionaryprofilepage',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missionaryprofilepage',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
