# Generated by Django 5.1.7 on 2025-04-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missionary_profiles', '0006_remove_missionaryprofilepage_donation_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionaryprofilepage',
            name='donation_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='missionaryprofilepage',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='missionaryprofilepage',
            name='personal_links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missionaryprofilepage',
            name='region',
            field=models.CharField(choices=[('Africa', 'Africa'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America'), ('Home Office', 'Home Office')], default='North America', max_length=50),
        ),
        migrations.AddField(
            model_name='missionaryprofilepage',
            name='special_project',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='missionaryprofilepage',
            name='video_links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
