# Generated by Django 5.1.7 on 2025-04-02 15:20

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missionary_profiles', '0007_missionaryprofilepage_donation_link_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionaryUpdatePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(auto_now_add=True)),
                ('content', wagtail.fields.RichTextField()),
                ('missionary_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='missionary_profiles.missionaryprofilepage')),
            ],
            options={
                'ordering': ['-date'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
