# Generated by Django 5.1.7 on 2025-04-02 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missionary_profiles', '0008_missionaryupdatepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionaryupdatepage',
            name='missionary_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missionary_updates', to='missionary_profiles.missionaryprofilepage'),
        ),
    ]
