# Generated by Django 5.1.7 on 2025-04-02 20:35

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missionary_profiles', '0010_remove_missionaryprofilepage_location_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionaryupdatepage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='missionaryupdatepage',
            name='missionary_profile',
        ),
        migrations.AddField(
            model_name='missionaryupdatepage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='missionaryupdatepage',
            name='information',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missionaryupdatepage',
            name='pdf_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AddField(
            model_name='missionaryupdatepage',
            name='pictures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='missionaryupdatepage',
            name='show_header',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='missionaryupdatepage',
            name='show_information',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='missionaryupdatepage',
            name='show_pictures',
            field=models.BooleanField(default=True),
        ),
    ]
