# Generated by Django 5.1.7 on 2025-04-03 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missionary_profiles', '0013_alter_missionaryupdatepage_header_image'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionaryupdatepage',
            name='missionary_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_updates', to='missionary_profiles.missionaryprofilepage'),
        ),
        migrations.AlterField(
            model_name='missionaryupdatepage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
