# Generated by Django 5.1.7 on 2025-04-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_contactpage_contactformfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformfield',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
