# Generated by Django 5.1.8 on 2025-08-25 17:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_homepage_home_values_image_homepage_values_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='values',
            field=wagtail.fields.StreamField([('value', 4), ('world_map', 15)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title of the value', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Description of the value', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Optional link for the value', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional background image for the value', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('link', 2), ('background_image', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title for the map section', 'required': False}), 6: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Display the title above the map', 'required': False}), 7: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL to navigate to when North America is clicked', 'required': False}), 8: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL to navigate to when South America is clicked', 'required': False}), 9: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL to navigate to when Europe is clicked', 'required': False}), 10: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL to navigate to when Africa is clicked', 'required': False}), 11: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL to navigate to when Asia is clicked', 'required': False}), 12: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL to navigate to when Oceania is clicked', 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Additional CSS classes for custom styling', 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'default': '440px', 'help_text': 'Height of the map (e.g., 440px, 50vh)', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('title', 5), ('show_title', 6), ('north_america_url', 7), ('south_america_url', 8), ('europe_url', 9), ('africa_url', 10), ('asia_url', 11), ('oceania_url', 12), ('css_class', 13), ('map_height', 14)]], {})}, help_text='Add, delete, or rearrange values for the Values section'),
        ),
    ]
