# Generated by Django 5.1.8 on 2025-08-25 18:03

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_homepage_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='home_map',
            field=wagtail.fields.StreamField([('world_map', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title for the map section', 'required': False}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Display the title above the map', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL to navigate to when North America is clicked', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL to navigate to when South America is clicked', 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL to navigate to when Europe is clicked', 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL to navigate to when Africa is clicked', 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL to navigate to when Asia is clicked', 'required': False}), 7: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL to navigate to when Oceania is clicked', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Additional CSS classes for custom styling', 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'default': '440px', 'help_text': 'Height of the map (e.g., 440px, 50vh)', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 0), ('show_title', 1), ('north_america_url', 2), ('south_america_url', 3), ('europe_url', 4), ('africa_url', 5), ('asia_url', 6), ('oceania_url', 7), ('css_class', 8), ('map_height', 9)]], {})}, help_text='Configure the world map for the Projects section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_home_map',
            field=models.BooleanField(default=True, help_text='Show or hide the world map in the Projects section'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='values',
            field=wagtail.fields.StreamField([('value', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title of the value', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Description of the value', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Optional link for the value', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional background image for the value', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('link', 2), ('background_image', 3)]], {})}, help_text='Add, delete, or rearrange values for the Values section'),
        ),
    ]
