# Generated by Django 5.1.8 on 2025-08-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_homepage_home_map_homepage_show_home_map_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='show_home_projects',
            field=models.BooleanField(default=True, help_text='Show or hide the Projects section'),
        ),
    ]
