# Generated by Django 5.1.13 on 2025-10-07 18:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_add_home_map_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='home_map',
            field=wagtail.fields.StreamField([('world_map', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional title for the map section', 'required': False}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Display the title above the map', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Additional CSS classes for custom styling', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': '440px', 'help_text': 'Height of the map (e.g., 440px, 50vh)', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('show_title', 1), ('css_class', 2), ('map_height', 3)]], {})}, help_text='Configure the world map for the Projects section'),
        ),
    ]
