# Generated by Django 5.2.12 on 2026-05-10 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_homepage_home_map'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='prayer_guide_document',
            field=models.ForeignKey(blank=True, help_text='Weekly prayer guide PDF (downloadable by visitors)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
    ]
