# Generated by Django 5.1.7 on 2025-04-01 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missionary_profiles', '0004_missionaryprofilepage_banner_image'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missionaryprofilepage',
            old_name='banner_image',
            new_name='profile_header_image',
        ),
        migrations.AddField(
            model_name='missionaryprofilepage',
            name='profile_info_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='missionaryprofilepage',
            name='profile_location_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
