# Generated by Django 5.1.7 on 2025-04-02 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missionary_profiles', '0011_remove_missionaryupdatepage_content_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missionaryupdatepage',
            options={},
        ),
        migrations.RemoveField(
            model_name='missionaryupdatepage',
            name='date',
        ),
        migrations.AddField(
            model_name='missionaryupdatepage',
            name='information_background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
