# Generated by Django 5.1.13 on 2025-11-17 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missionary_profiles', '0015_missionaryprofilegalleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionaryNewsletterSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
                ('missionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_signups', to='missionary_profiles.missionaryprofilepage')),
            ],
        ),
    ]
