# Generated by Django 5.1.13 on 2025-11-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missionary_profiles', '0016_missionarynewslettersignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionarynewslettersignup',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='missionarynewslettersignup',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
