# Generated by Django 5.2.11 on 2026-02-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missionary_profiles', '0018_alter_missionaryupdatepage_pictures_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionaryupdatepage',
            name='pictures',
        ),
    ]
