# Generated by Django 5.1.8 on 2026-05-11 03:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missionary_profiles', '0020_missionaryprofilepage_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionaryprofilepage',
            name='information_sections',
            field=wagtail.fields.StreamField([('section', 2), ('person_profile', 5), ('scripture', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Example: OUR MISSION', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Example: Colby', 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Example: Hands-on mechanical, strategist, pianist', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('name', 3), ('summary_line', 4), ('bio', 1)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'One of our favorite verses', 'required': False}), 7: ('wagtail.blocks.TextBlock', (), {'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Example: 1 Corinthians 15:1-3 NASB1995', 'required': True}), 9: ('wagtail.blocks.StructBlock', [[('intro', 6), ('verse_text', 7), ('reference', 8)]], {})}),
        ),
        migrations.AlterField(
            model_name='missionaryprofilepage',
            name='information',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
